//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppServices.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppServices.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInfoPlaceholder {
            get {
                return ResourceManager.GetString("AdditionalInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string BathroomCount_Four {
            get {
                return ResourceManager.GetString("BathroomCount_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string BathroomCount_One {
            get {
                return ResourceManager.GetString("BathroomCount_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string BathroomCount_Three {
            get {
                return ResourceManager.GetString("BathroomCount_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string BathroomCount_Two {
            get {
                return ResourceManager.GetString("BathroomCount_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Bathrooms.
        /// </summary>
        public static string Bathrooms {
            get {
                return ResourceManager.GetString("Bathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for Bathrooms..
        /// </summary>
        public static string Bathrooms_Required {
            get {
                return ResourceManager.GetString("Bathrooms_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Password.
        /// </summary>
        public static string ChoosePassword {
            get {
                return ResourceManager.GetString("ChoosePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Address.
        /// </summary>
        public static string CleaningAddress {
            get {
                return ResourceManager.GetString("CleaningAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        public static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm I have read and agreed to the Terms and Conditions.
        /// </summary>
        public static string ConfirmTermsAndConditions {
            get {
                return ResourceManager.GetString("ConfirmTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person&apos;s Email.
        /// </summary>
        public static string ContactPersonEmail {
            get {
                return ResourceManager.GetString("ContactPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person&apos;s Family Name.
        /// </summary>
        public static string ContactPersonFamilyName {
            get {
                return ResourceManager.GetString("ContactPersonFamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person&apos;s First Name.
        /// </summary>
        public static string ContactPersonFirstName {
            get {
                return ResourceManager.GetString("ContactPersonFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person&apos;s Phone Number.
        /// </summary>
        public static string ContactPersonPhoneNumber {
            get {
                return ResourceManager.GetString("ContactPersonPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Code (optional).
        /// </summary>
        public static string EntryCodeOptional {
            get {
                return ResourceManager.GetString("EntryCodeOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for ExtraRooms..
        /// </summary>
        public static string ExtraRooms_Required {
            get {
                return ResourceManager.GetString("ExtraRooms_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor and Door (optional).
        /// </summary>
        public static string FloorAndDoorOptional {
            get {
                return ResourceManager.GetString("FloorAndDoorOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Type.
        /// </summary>
        public static string FloorType {
            get {
                return ResourceManager.GetString("FloorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string FloorType_Carpet {
            get {
                return ResourceManager.GetString("FloorType_Carpet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linoleum / PVC.
        /// </summary>
        public static string FloorType_LinoleumPVC {
            get {
                return ResourceManager.GetString("FloorType_LinoleumPVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parquet / Laminate.
        /// </summary>
        public static string FloorType_ParquetLaminate {
            get {
                return ResourceManager.GetString("FloorType_ParquetLaminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for Floor Type..
        /// </summary>
        public static string FloorType_Required {
            get {
                return ResourceManager.GetString("FloorType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles / Ceramic.
        /// </summary>
        public static string FloorType_TilesCeramic {
            get {
                return ResourceManager.GetString("FloorType_TilesCeramic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Key.
        /// </summary>
        public static string HideKey {
            get {
                return ResourceManager.GetString("HideKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Number.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get the key.
        /// </summary>
        public static string HowToGetKey {
            get {
                return ResourceManager.GetString("HowToGetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Pick Up.
        /// </summary>
        public static string KeyPickUp {
            get {
                return ResourceManager.GetString("KeyPickUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Rooms.
        /// </summary>
        public static string OtherRooms {
            get {
                return ResourceManager.GetString("OtherRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attic.
        /// </summary>
        public static string OtherRoomType_Attic {
            get {
                return ResourceManager.GetString("OtherRoomType_Attic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basement.
        /// </summary>
        public static string OtherRoomType_Basement {
            get {
                return ResourceManager.GetString("OtherRoomType_Basement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage.
        /// </summary>
        public static string OtherRoomType_Garage {
            get {
                return ResourceManager.GetString("OtherRoomType_Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry Room.
        /// </summary>
        public static string OtherRoomType_LaundryRoom {
            get {
                return ResourceManager.GetString("OtherRoomType_LaundryRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailbox.
        /// </summary>
        public static string OtherRoomType_Mailbox {
            get {
                return ResourceManager.GetString("OtherRoomType_Mailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string OurServices {
            get {
                return ResourceManager.GetString("OurServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution Level.
        /// </summary>
        public static string PollutionLevel {
            get {
                return ResourceManager.GetString("PollutionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string PollutionLevel_Clean {
            get {
                return ResourceManager.GetString("PollutionLevel_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirty.
        /// </summary>
        public static string PollutionLevel_Dirty {
            get {
                return ResourceManager.GetString("PollutionLevel_Dirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PollutionLevel_Medium {
            get {
                return ResourceManager.GetString("PollutionLevel_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for PollutionLevel..
        /// </summary>
        public static string PollutionLevel_Required {
            get {
                return ResourceManager.GetString("PollutionLevel_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Dirty.
        /// </summary>
        public static string PollutionLevel_VeryDirty {
            get {
                return ResourceManager.GetString("PollutionLevel_VeryDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Key.
        /// </summary>
        public static string PostKey {
            get {
                return ResourceManager.GetString("PostKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string RoomCount_Five {
            get {
                return ResourceManager.GetString("RoomCount_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.5.
        /// </summary>
        public static string RoomCount_FiveAndHalf {
            get {
                return ResourceManager.GetString("RoomCount_FiveAndHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoomCount_Four {
            get {
                return ResourceManager.GetString("RoomCount_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.5.
        /// </summary>
        public static string RoomCount_FourAndHalf {
            get {
                return ResourceManager.GetString("RoomCount_FourAndHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string RoomCount_House {
            get {
                return ResourceManager.GetString("RoomCount_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RoomCount_One {
            get {
                return ResourceManager.GetString("RoomCount_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        public static string RoomCount_OneAndHalf {
            get {
                return ResourceManager.GetString("RoomCount_OneAndHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string RoomCount_Six {
            get {
                return ResourceManager.GetString("RoomCount_Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RoomCount_Three {
            get {
                return ResourceManager.GetString("RoomCount_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.5.
        /// </summary>
        public static string RoomCount_ThreeAndHalf {
            get {
                return ResourceManager.GetString("RoomCount_ThreeAndHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomCount_Two {
            get {
                return ResourceManager.GetString("RoomCount_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.
        /// </summary>
        public static string RoomCount_TwoAndHalf {
            get {
                return ResourceManager.GetString("RoomCount_TwoAndHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for Rooms..
        /// </summary>
        public static string Rooms_Required {
            get {
                return ResourceManager.GetString("Rooms_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone will be at the address.
        /// </summary>
        public static string SomeoneAtAddress {
            get {
                return ResourceManager.GetString("SomeoneAtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrace / Balcony.
        /// </summary>
        public static string Terrace {
            get {
                return ResourceManager.GetString("Terrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass or Window Cleaning.
        /// </summary>
        public static string TerraceType_GlassOrWindowCleaning {
            get {
                return ResourceManager.GetString("TerraceType_GlassOrWindowCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pressure.
        /// </summary>
        public static string TerraceType_HighPressure {
            get {
                return ResourceManager.GetString("TerraceType_HighPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Clean.
        /// </summary>
        public static string TerraceType_SweptClean {
            get {
                return ResourceManager.GetString("TerraceType_SweptClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number (optional).
        /// </summary>
        public static string VATNumberOptional {
            get {
                return ResourceManager.GetString("VATNumberOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Type.
        /// </summary>
        public static string WindowType {
            get {
                return ResourceManager.GetString("WindowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blinds.
        /// </summary>
        public static string WindowType_Blinds {
            get {
                return ResourceManager.GetString("WindowType_Blinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a value for Window Type..
        /// </summary>
        public static string WindowType_Required {
            get {
                return ResourceManager.GetString("WindowType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller Shutters.
        /// </summary>
        public static string WindowType_RollerShutters {
            get {
                return ResourceManager.GetString("WindowType_RollerShutters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Shutters.
        /// </summary>
        public static string WindowType_WindowShutters {
            get {
                return ResourceManager.GetString("WindowType_WindowShutters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter Garden.
        /// </summary>
        public static string WinterGarden {
            get {
                return ResourceManager.GetString("WinterGarden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glass or Window Cleaning.
        /// </summary>
        public static string WinterGardenType_GlassOrWindowCleaning {
            get {
                return ResourceManager.GetString("WinterGardenType_GlassOrWindowCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Pressure.
        /// </summary>
        public static string WinterGardenType_HighPressure {
            get {
                return ResourceManager.GetString("WinterGardenType_HighPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swept Clean.
        /// </summary>
        public static string WinterGardenType_SweptClean {
            get {
                return ResourceManager.GetString("WinterGardenType_SweptClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Handover Guarantee.
        /// </summary>
        public static string WithHandoverGuarantee {
            get {
                return ResourceManager.GetString("WithHandoverGuarantee", resourceCulture);
            }
        }
    }
}
